train_path: "data/deft09_parlement_appr"
test_path: "data/deft09_parlement_test"

languages:
  - "fr"  # French
  - "en"  # English
  - "it"  # Italian

models:
  #- "NB"           # Complement Naive Bayes
  - "RFC"          # Random Forest Classifier
  - "SVM"          # Support Vector Machine
  - "LR"           # Logistic Regression
  - "Perceptron"   # Perceptron Algorithm

drop_duplicates: true
downsample: true
vectorizer: "bert" #tfidf or doc2vec or bert
